global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'sinkhole'
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: [ 'localhost:8000' ]
